// clocks.c — Arduino Nano R4 (Renesas RA4M1) port of the TimbreOS time base.
//
// ─────────────────────────────────────────────────────────────────────────────
// CLOCK ARCHITECTURE
// ─────────────────────────────────────────────────────────────────────────────
// Two GPT channels, both running directly off PCLKD/1024.
//
//   tick_timer  — GPT0, 32-bit free-running uptime counter.
//                 PCLKD/1024 @ 32 MHz → 31.25 kHz → 32 µs/tick.
//                 Period = 0x7FFFFFFF (rollover ≈ 38 hours).
//   delta_timer — GPT2, 16-bit one-shot alarm used by set_delta_alarm().
//                 PCLKD/1024 @ 32 MHz, same 32 µs tick units.
//                 Max one-shot period ≈ 2.097 s (0xFFFF ticks);
//                 longer alarms re-arm via the scheduler.
//
// RTC integration is stubbed (set_utc / print_RTC) until the r_rtc stack is
// brought online.
//
// ─────────────────────────────────────────────────────────────────────────────
// NOTES ACCUMULATED DURING BRING-UP (read before touching GPT/ELC config)
// ─────────────────────────────────────────────────────────────────────────────
//
// 1. ONE_SECOND is 31250 (see Board/project_defs.h), matching PCLKD/1024 at
//    32 MHz (32 µs/tick). If the board clock tree changes, update both.
//
// 2. On RA4M1 the GPT_SOURCE_GPT_A … GPT_SOURCE_GPT_H enums are *fixed
//    hardware ELC slots*, NOT "pick any GPT channel by letter". An earlier
//    attempt to cascade GPT3 → GPT0/GPT2 via GPT_SOURCE_GPT_A left both
//    downstream counters stuck at zero. If you need a slower tick, use
//    source_div (PCLKD prescaler /1, /2, /4, /8, /16, /32, /64, /256, /1024)
//    — don't try to cascade channels.
//
// 3. The Arduino DFU bootloader hands control to user code with
//    PRIMASK = 1 (IRQs globally masked). FSP's SystemInit() does NOT clear
//    it. Without an explicit __enable_irq() early in hal_entry(), the GPT2
//    alarm ISR never dispatches — the first heartbeat runs (because it
//    fires synchronously off later()), then the scheduler freezes waiting
//    for an IRQ that can't preempt. Fix lives in src/hal_entry.c.
//
// 4. hal_data.c (generated by RASC) and memory_regions.ld have HAND EDITS:
//      · delta_timer  mode        = TIMER_MODE_ONE_SHOT
//      · delta_timer  source_div  = 10     (/1024)
//      · delta_timer  cycle_end_ipl = 12   (IPL 0 is treated as "disabled")
//      · delta_timer  count_up_source / clear_source = GPT_SOURCE_NONE
//      · tick_timer   source_div  = 10     (/1024)
//      · tick_timer   count_up_source / clear_source = GPT_SOURCE_NONE
//      · memory_regions.ld: FLASH_START 0x4400, FLASH_GAP 0x4000..0x4400,
//        all OPTION_SETTING_*_LENGTH = 0 (Arduino bootloader owns 0x0..0x3FFF).
//    Re-running "Generate Project Content" in RASC will clobber both files.
//    See Nano/README-RASC.md for the recovery procedure.

#include "hal_data.h"
#include "r_ioport.h"

#include "tea.h"
#include "printers.h"
#include "cli.h"
#include "project_defs.h"
#include <time.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

// IOPORT is opened by RASC's hal_warmstart.c before main() runs — we just
// reach into the generated g_ioport_ctrl for PinWrite calls. No R_IOPORT_Open
// here.

// Nano R4 user LED — yellow, on port 2 pin 4 (P204), configured in RASC.
#define LED_PIN  BSP_IO_PORT_02_PIN_04

void print_RTC();
void delta_timer_cb(timer_callback_args_t * p_args);

// GPT2 (delta_timer) is 16-bit — clamp alarm periods to 0xFFFF ticks.
// At PCLKD/1024 = 31.25 kHz, that's ~2.097 s max one-shot; longer alarms
// are re-armed by the scheduler.
#define DELTA_MAX_TICKS  0xFFFFu

// ── UTC time-of-build helper ───────────────────────────────────────────────
// Parse __TIMESTAMP__ string ("Www Mmm DD HH:MM:SS YYYY") into a UTC Unix timestamp.
static Long timestamp_to_utc(const char *ts) {
    static const char * const mon_names[] = {
        "Jan","Feb","Mar","Apr","May","Jun",
        "Jul","Aug","Sep","Oct","Nov","Dec"
    };
    struct tm t = {0};
    char wday[4], mon[4];
    int day, hour, min, sec, year;

    sscanf(ts, "%3s %3s %d %d:%d:%d %d",
           wday, mon, &day, &hour, &min, &sec, &year);

    t.tm_mday  = day;
    t.tm_hour  = hour;
    t.tm_min   = min;
    t.tm_sec   = sec;
    t.tm_year  = year - 1900;
    t.tm_isdst = 0;
    for (int i = 0; i < 12; i++) {
        if (strncmp(mon, mon_names[i], 3) == 0) { t.tm_mon = i; break; }
    }
    // mktime() on newlib bare-metal treats struct tm as UTC (no tz offset)
    return (Long)mktime(&t);
}

// STUB: RTC integration deferred. Replace with R_RTC_CalendarTimeSet(&g_rtc0_ctrl, ...)
// once the r_rtc stack is opened and we have a Unix-epoch → struct tm helper.
void set_utc(Long utc) {
    (void)utc;
}

void over_due() { /* incCtr(overDueTea); */ }

// ── delta alarm (one-shot GPT2) ─────────────────────────────────────────────
//
// Translate a delta (in ticks) into a one-shot GPT2 period and fire. GPT2 is
// 16-bit, so periods > 0xFFFF are clamped; the TEA scheduler re-arms when
// this shorter alarm fires.
void set_delta_alarm(Long t) {
    if (t > DELTA_MAX_TICKS) {
        print("#");
        t = DELTA_MAX_TICKS;
    }
    if (t < 1) t = 1;
    R_GPT_PeriodSet(&delta_timer_ctrl, (uint32_t)t);
    R_GPT_Reset    (&delta_timer_ctrl);
    R_GPT_Start    (&delta_timer_ctrl);   // one-shot — stops itself at TRG
}

// Called from delta_timer_cb (FSP callback, below). Signals the scheduler.
void delta_alarm() {
    now(*alarmEvent);
}

// ── FSP callback trampoline ────────────────────────────────────────────────
//
// Name matches RASC's GPT2 `p_callback` field in ra_gen/hal_data.c.
void delta_timer_cb(timer_callback_args_t * p_args) {
    if (p_args->event == TIMER_EVENT_CYCLE_END) {
        delta_alarm();
    }
}

// ── uptime in 32 µs ticks ───────────────────────────────────────────────────
Long get_ticks() {
    timer_status_t s;
    R_GPT_StatusGet(&tick_timer_ctrl, &s);
    return (Long)s.counter;
}

// ── diagnostic ─────────────────────────────────────────────────────────────
void show_timer() {
    print("  ticks/S:");
    printDec(ONE_SECOND);
    print("  ticks:");
    printDec(get_ticks());
    print("  "), print_RTC();
}

// WFI is portable across Cortex-M — sleeps until any interrupt wakes the core.
void micro_sleep() { __WFI(); }

// ── LED heartbeat ──────────────────────────────────────────────────────────
// Nano R4 yellow LED on P204. Classic two-flash heartbeat — short-on, short-gap,
// short-on, long-gap.
#define ON_TIME 2
static inline void led_on (void) { R_IOPORT_PinWrite(&g_ioport_ctrl, LED_PIN, BSP_IO_LEVEL_HIGH); }
static inline void led_off(void) { R_IOPORT_PinWrite(&g_ioport_ctrl, LED_PIN, BSP_IO_LEVEL_LOW);  }

static void blink_leds() {
    Long t;
    static enum {GREEN1,SPACE1,GREEN2,SPACE2} color = SPACE2;
    switch (color) {
    case GREEN1:  led_on();  color = SPACE1; t = ON_TIME;       break;
    case SPACE1:  led_off(); color = GREEN2; t = 200 - ON_TIME; break;
    case GREEN2:  led_on();  color = SPACE2; t = ON_TIME;       break;
    default:
    case SPACE2:  led_off(); color = GREEN1; t = 800 - ON_TIME; break;
    }
    in(msec(t), blink_leds);
}

void blink();
// ── init ───────────────────────────────────────────────────────────────────
void init_clocks() {
    // IOPORT was opened by R_BSP_WarmStart() during BSP bring-up, before main().
    // DWT cycle counter was enabled in hal_entry.c.
    never(alarmEvent);

    // tick_timer: 32-bit free-running counter in 32 µs units (PCLKD/1024).
    R_GPT_Open  (&tick_timer_ctrl, &tick_timer_cfg);
    R_GPT_Start (&tick_timer_ctrl);

    // delta_timer: 16-bit one-shot, started on demand by set_delta_alarm().
    R_GPT_Open  (&delta_timer_ctrl, &delta_timer_cfg);

    later(blink_leds);
    namedAction(blink_leds);

    // NOTE: do not print() here — init_clocks runs before
    // usart_transport_init(), so emitq has no drain path and output() will
    // spin forever if we enqueue anything. The build banner is printed from
    // hal_entry() after the transport is up.
//    set_utc(timestamp_to_utc(__TIMESTAMP__));
}

// Print the build timestamp banner. Safe to call ONLY after
// usart_transport_init() has wired up the output() drain.
void print_build_banner(void) {
    print("\nBuilt: "), print(__TIMESTAMP__);
}
