// clocks.c — Arduino Nano R4 (Renesas RA4M1) port of the TimbreOS time base.
//
// ─────────────────────────────────────────────────────────────────────────────
// CLOCK ARCHITECTURE
// ─────────────────────────────────────────────────────────────────────────────
// Two GPT channels, both running directly off PCLKD/1024.
//
//   tick_timer  — GPT0, 32-bit free-running uptime counter.
//                 PCLKD/1024 @ 32 MHz → 31.25 kHz → 32 µs/tick.
//                 Period = 0x7FFFFFFF (rollover ≈ 38 hours).
//   delta_timer — GPT2, 16-bit one-shot alarm used by set_delta_alarm().
//                 PCLKD/1024 @ 32 MHz, same 32 µs tick units.
//                 Max one-shot period ≈ 2.097 s (0xFFFF ticks);
//                 longer alarms re-arm via the scheduler.
//
// RTC integration is stubbed (set_utc / print_RTC) until the r_rtc stack is
// brought online.
//
// ─────────────────────────────────────────────────────────────────────────────
// NOTES ACCUMULATED DURING BRING-UP (read before touching GPT/ELC config)
// ─────────────────────────────────────────────────────────────────────────────
//
// 1. ONE_SECOND is 31250 (see Board/project_defs.h), matching PCLKD/1024 at
//    32 MHz (32 µs/tick). If the board clock tree changes, update both.
//
// 2. On RA4M1 the GPT_SOURCE_GPT_A … GPT_SOURCE_GPT_H enums are *fixed
//    hardware ELC slots*, NOT "pick any GPT channel by letter". An earlier
//    attempt to cascade GPT3 → GPT0/GPT2 via GPT_SOURCE_GPT_A left both
//    downstream counters stuck at zero. If you need a slower tick, use
//    source_div (PCLKD prescaler /1, /2, /4, /8, /16, /32, /64, /256, /1024)
//    — don't try to cascade channels.
//
// 3. The Arduino DFU bootloader hands control to user code with
//    PRIMASK = 1 (IRQs globally masked). FSP's SystemInit() does NOT clear
//    it. Without an explicit __enable_irq() early in hal_entry(), the GPT2
//    alarm ISR never dispatches — the first heartbeat runs (because it
//    fires synchronously off later()), then the scheduler freezes waiting
//    for an IRQ that can't preempt. Fix lives in src/hal_entry.c.
//
// 4. hal_data.c (generated by RASC) and memory_regions.ld have HAND EDITS:
//      · delta_timer  mode        = TIMER_MODE_ONE_SHOT
//      · delta_timer  source_div  = 10     (/1024)
//      · delta_timer  cycle_end_ipl = 12   (IPL 0 is treated as "disabled")
//      · delta_timer  count_up_source / clear_source = GPT_SOURCE_NONE
//      · tick_timer   source_div  = 10     (/1024)
//      · tick_timer   count_up_source / clear_source = GPT_SOURCE_NONE
//      · memory_regions.ld: FLASH_START 0x4400, FLASH_GAP 0x4000..0x4400,
//        all OPTION_SETTING_*_LENGTH = 0 (Arduino bootloader owns 0x0..0x3FFF).
//    Re-running "Generate Project Content" in RASC will clobber both files.
//    See Nano/README-RASC.md for the recovery procedure.

#include "hal_data.h"
#include "r_ioport.h"

#include "tea.h"
#include "printers.h"
#include "cli.h"
#include "clocks.h"
#include "project_defs.h"
// Intentionally NOT including <time.h>: newlib's mktime/tzset can hang on
// bare-metal. See timestamp_to_utc() below for the hand-rolled replacement.
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

// IOPORT is opened by RASC's hal_warmstart.c before main() runs — we just
// reach into the generated g_ioport_ctrl for PinWrite calls. No R_IOPORT_Open
// here.

// Nano R4 user LED — yellow, on port 2 pin 4 (P204), configured in RASC.
#define LED_PIN  BSP_IO_PORT_02_PIN_04

void print_RTC();
void delta_timer_cb(timer_callback_args_t * p_args);

// GPT2 (delta_timer) is 16-bit — clamp alarm periods to 0xFFFF ticks.
// At PCLKD/1024 = 31.25 kHz, that's ~2.097 s max one-shot; longer alarms
// are re-armed by the scheduler.
#define DELTA_MAX_TICKS  0xFFFFu

// ── UTC time-of-build helper ───────────────────────────────────────────────
//
// DO NOT call newlib's mktime(), tzset(), or sscanf() here. On bare-metal
// newlib:
//   · mktime()/tzset() pull in lock retargeting and sometimes _sbrk /
//     _gettimeofday. If those aren't fully satisfied at link time the call
//     spins forever.
//   · sscanf() drags in the full stdio FILE machinery, locale init, and in
//     some builds _malloc_r / _sbrk_r. If the heap isn't wired up the
//     malloc retry path can also spin forever.
// Observed symptom of both: init_clocks() never returns, firmware hangs
// silently between boot_alive_blink and usart_transport_init — no output,
// no heartbeat, no hint that the hang is inside a time-conversion call.
//
// __TIMESTAMP__ has a rigid fixed-width format — "Www Mmm DD HH:MM:SS YYYY"
// — so a fixed-offset positional parser does the job with zero libc.
static Long timestamp_to_utc(const char *ts) {
    static const char mon_names[12][3] = {
        {'J','a','n'},{'F','e','b'},{'M','a','r'},{'A','p','r'},
        {'M','a','y'},{'J','u','n'},{'J','u','l'},{'A','u','g'},
        {'S','e','p'},{'O','c','t'},{'N','o','v'},{'D','e','c'}
    };
    // Tiny positional decimal reader: skips any non-digit (covers the
    // space-padded single-digit day that some compilers emit).
    #define DIG(c) ((c) >= '0' && (c) <= '9' ? (c) - '0' : 0)

    // Offsets:  "Www Mmm DD HH:MM:SS YYYY"
    //            0   4   8  11 14 17 20
    int day   = DIG(ts[8])  * 10 + DIG(ts[9]);
    int hour  = DIG(ts[11]) * 10 + DIG(ts[12]);
    int min   = DIG(ts[14]) * 10 + DIG(ts[15]);
    int sec   = DIG(ts[17]) * 10 + DIG(ts[18]);
    int year  = DIG(ts[20]) * 1000 + DIG(ts[21]) * 100
              + DIG(ts[22]) * 10   + DIG(ts[23]);
    #undef DIG

    int month = 1;
    for (int i = 0; i < 12; i++) {
        if (ts[4] == mon_names[i][0] &&
            ts[5] == mon_names[i][1] &&
            ts[6] == mon_names[i][2]) {
            month = i + 1;
            break;
        }
    }

    // Howard Hinnant's days_from_civil — returns days since 1970-01-01,
    // correct for the full proleptic Gregorian range, no libc calls.
    int y   = (month <= 2) ? (year - 1) : year;
    int era = (y >= 0 ? y : y - 399) / 400;
    unsigned yoe = (unsigned)(y - era * 400);                          // [0, 399]
    unsigned doy = (153u * (unsigned)(month + (month > 2 ? -3 : 9)) + 2u) / 5u
                 + (unsigned)(day - 1);                                // [0, 365]
    unsigned doe = yoe * 365u + yoe / 4u - yoe / 100u + doy;           // [0, 146096]
    long days = (long)era * 146097L + (long)doe - 719468L;             // epoch 1970-01-01

    return (Long)(days * 86400L + (long)hour * 3600L + (long)min * 60L + (long)sec);
}

// ── Software-maintained UTC ────────────────────────────────────────────────
//
// No hardware RTC is open yet (deferred until the r_rtc stack is wired up).
// Instead we maintain UTC in software, seeded from the build timestamp in
// init_clocks() via set_utc(timestamp_to_utc(__TIMESTAMP__)).
//
// State model:
//   boot_utc = UTC epoch value that corresponds to tick-counter == 0.
//   current  = boot_utc + (accumulated_ticks / ONE_SECOND).
//
// The tick counter (GPT0) is 32-bit and rolls over every ~38 hours at
// 32 µs/tick. We extend it to 64 bits in software by detecting wrap on each
// call to extended_ticks(). That requires extended_ticks() to be called at
// least once per rollover period — init_clocks() schedules a periodic tick
// (utc_heartbeat) every few minutes so the wrap never slips past us even
// when no CLI user is prodding show-time.
//
// When the RTC stack is opened, replace the body of tick_get_utc() with
// R_RTC_CalendarTimeGet() and the civil-to-epoch conversion, and drop the
// extended_ticks() machinery.
static Long boot_utc = 0;

static uint64_t extended_ticks(void) {
    static uint32_t last_low = 0;
    static uint64_t high     = 0;
    uint64_t result;
    // ENTER_REGION / LEAVE_REGION expand to a compound { ... } block, so any
    // variable we want to read AFTER the region must be declared before it.
    ENTER_REGION()
    uint32_t now = (uint32_t)get_ticks();
    if (now < last_low) {
        high += 0x100000000ULL;   // tick_timer wrapped
    }
    last_low = now;
    result = high + now;
    LEAVE_REGION()
    return result;
}

void set_utc(Long utc) {
    uint64_t t = extended_ticks();
    boot_utc = utc - (Long)(t / (uint64_t)ONE_SECOND);
}

Long tick_get_utc(void) {
    uint64_t t = extended_ticks();
    return boot_utc + (Long)(t / (uint64_t)ONE_SECOND);
}

// Periodic poke so extended_ticks() never goes more than a few minutes
// between observations — guarantees we never miss a 32-bit rollover.
static void utc_heartbeat(void) {
    (void)extended_ticks();
    in(secs(600), utc_heartbeat);   // every 10 minutes
}

void over_due() { /* incCtr(overDueTea); */ }

// ── delta alarm (one-shot GPT2) ─────────────────────────────────────────────
//
// Translate a delta (in ticks) into a one-shot GPT2 period and fire. GPT2 is
// 16-bit, so periods > 0xFFFF are clamped; the TEA scheduler re-arms when
// this shorter alarm fires.
void set_delta_alarm(Long t) {
    if (t > DELTA_MAX_TICKS) {
        print("#");
        t = DELTA_MAX_TICKS;
    }
    if (t < 1) t = 1;
    R_GPT_PeriodSet(&delta_timer_ctrl, (uint32_t)t);
    R_GPT_Reset    (&delta_timer_ctrl);
    R_GPT_Start    (&delta_timer_ctrl);   // one-shot — stops itself at TRG
}

// Called from delta_timer_cb (FSP callback, below). Signals the scheduler.
void delta_alarm() {
    now(*alarmEvent);
}

// ── FSP callback trampoline ────────────────────────────────────────────────
//
// Name matches RASC's GPT2 `p_callback` field in ra_gen/hal_data.c.
void delta_timer_cb(timer_callback_args_t * p_args) {
    if (p_args->event == TIMER_EVENT_CYCLE_END) {
        delta_alarm();
    }
}

// ── uptime in 32 µs ticks ───────────────────────────────────────────────────
Long get_ticks() {
    timer_status_t s;
    R_GPT_StatusGet(&tick_timer_ctrl, &s);
    return (Long)s.counter;
}

// ── diagnostic ─────────────────────────────────────────────────────────────
void show_timer() {
    print("  ticks/S:");
    printDec(ONE_SECOND);
    print("  ticks:");
    printDec(get_ticks());
    print("  UTC:");
    printDec(get_utc());
    print("  ");
    print_RTC();
}

// WFI is portable across Cortex-M — sleeps until any interrupt wakes the core.
void micro_sleep() { __WFI(); }

// ── LED heartbeat ──────────────────────────────────────────────────────────
// Nano R4 yellow LED on P204. Classic two-flash heartbeat — short-on, short-gap,
// short-on, long-gap.
#define ON_TIME 2
static inline void led_on (void) { R_IOPORT_PinWrite(&g_ioport_ctrl, LED_PIN, BSP_IO_LEVEL_HIGH); }
static inline void led_off(void) { R_IOPORT_PinWrite(&g_ioport_ctrl, LED_PIN, BSP_IO_LEVEL_LOW);  }

static void blink_leds() {
    Long t;
    static enum {GREEN1,SPACE1,GREEN2,SPACE2} color = SPACE2;
    switch (color) {
    case GREEN1:  led_on();  color = SPACE1; t = ON_TIME;       break;
    case SPACE1:  led_off(); color = GREEN2; t = 200 - ON_TIME; break;
    case GREEN2:  led_on();  color = SPACE2; t = ON_TIME;       break;
    default:
    case SPACE2:  led_off(); color = GREEN1; t = 800 - ON_TIME; break;
    }
    in(msec(t), blink_leds);
}

// ── init ───────────────────────────────────────────────────────────────────
void init_clocks() {
    // IOPORT was opened by R_BSP_WarmStart() during BSP bring-up, before main().
    // DWT cycle counter was enabled in hal_entry.c.
    never(alarmEvent);

    // tick_timer: 32-bit free-running counter in 32 µs units (PCLKD/1024).
    R_GPT_Open  (&tick_timer_ctrl, &tick_timer_cfg);
    R_GPT_Start (&tick_timer_ctrl);

    // delta_timer: 16-bit one-shot, started on demand by set_delta_alarm().
    R_GPT_Open  (&delta_timer_ctrl, &delta_timer_cfg);

    later(blink_leds);
    namedAction(blink_leds);

    // NOTE: do not print() here — init_clocks runs before
    // usart_transport_init(), so emitq has no drain path and output() will
    // spin forever if we enqueue anything. The build banner is printed from
    // hal_entry() after the transport is up.
    //
    // timestamp_to_utc() is safe to call here — it's pure arithmetic. It
    // does NOT call newlib's mktime() or sscanf(), which hang on bare-metal
    // (see the comment block above the function definition).
    set_utc(timestamp_to_utc(__TIMESTAMP__));

    // Arm the periodic 32→64-bit rollover tracker; see extended_ticks().
    later(utc_heartbeat);
    namedAction(utc_heartbeat);
}

// Print the build timestamp banner. Safe to call ONLY after
// usart_transport_init() has wired up the output() drain.
void print_build_banner(void) {
    print("\nBuilt: "), print(__TIMESTAMP__);
}
