#include "hal_data.h"
#include "r_ioport.h"

#include "tea.h"
#include "cli.h"
#include "clocks.h"
#include "cli_transport_usart.h"

// init_cli is defined in TimbreOS/cli.c but not declared in cli.h —
// follow the convention used by the other board ports.
void init_cli(void);

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
/* ── DIAGNOSTIC: "is the firmware alive?" bring-up blink ────────────────────
 * Three fast on/off cycles on the yellow LED (P204) before any TimbreOS
 * init runs. If you see three quick blinks after reset, hal_entry is being
 * called and IOPORT is opened — any later silence is a downstream bug.
 * Remove once things are known-good.
 */
static void boot_blink_diag(void)
{
    for (int i = 0; i < 3; i++) {
        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_02_PIN_04, BSP_IO_LEVEL_HIGH);
        for (volatile uint32_t w = 0; w < 600000; w++) { __asm volatile ("nop"); }
        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_02_PIN_04, BSP_IO_LEVEL_LOW);
        for (volatile uint32_t w = 0; w < 600000; w++) { __asm volatile ("nop"); }
    }
}

/* Short, FAST pulses — distinct from boot_blink_diag's slow pulses. Call
 * with count=N to count "I completed init step N". If you see fewer pulses
 * than expected, the missing step is where we hung. */
void diag_pulse(int count)
{
    /* Long-ish gap so groups are visually separable from each other. */
    for (volatile uint32_t w = 0; w < 2000000; w++) { __asm volatile ("nop"); }
    for (int i = 0; i < count; i++) {
        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_02_PIN_04, BSP_IO_LEVEL_HIGH);
        for (volatile uint32_t w = 0; w < 150000; w++) { __asm volatile ("nop"); }
        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_02_PIN_04, BSP_IO_LEVEL_LOW);
        for (volatile uint32_t w = 0; w < 250000; w++) { __asm volatile ("nop"); }
    }
}

void hal_entry(void)
{
    /* Prove we booted — before we touch the scheduler or clocks. */
    boot_blink_diag();

    /* Enable the DWT cycle counter for hi-res timing (sysTicks()).
     * Required by project_defs.h: #define sysTicks() (Long)(DWT->CYCCNT) */
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT = 0;
    DWT->CTRL   |= DWT_CTRL_CYCCNTENA_Msk;
    diag_pulse(1);   /* 1 quick: DWT setup returned */

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif

    /* ── TimbreOS bring-up ────────────────────────────────────────────────
     * init_tea() calls init_clocks() internally (see TimbreOS/tea.c:585) so
     * we do NOT call init_clocks() again here. init_clocks itself contains
     * a diag_pulse(2) marker near its end (Board/clocks.c) — if we see a
     * "2" group without a following "3" group, init_tea's post-clocks tail
     * (namedAction / when / later) is the offender.
     *
     *   diag pattern:
     *     3 slow (boot)
     *     1 quick              → DWT setup OK
     *     2 quick (from inside init_clocks) → GPTs opened and LED scheduled
     *     3 quick              → init_tea tail returned
     *     4 quick              → usart_transport_init returned
     *     5 quick              → init_cli returned
     *     yellow heartbeat     → scheduler running
     */
    init_tea();              diag_pulse(3);
    usart_transport_init();  diag_pulse(4);
    init_cli();              diag_pulse(5);

    while (1) {
        /* BISECT: force-clear PRIMASK each iteration to test "PRIMASK stuck"
         * theory. If heartbeat keeps ticking with this in place, something in
         * the safe()/ENTER_SAFE_REGION chain is leaving IRQs masked. */
        __enable_irq();
        run();
        micro_sleep();   // __WFI — wake on any interrupt (timer, UART RX/TX)
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
